import "@/app/ui/globals.css";
import type { Metadata } from "next";
import { vt323 } from "@/app/ui/fonts";
import { pressStart2P } from "@/app/ui/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${vt323.className} ${pressStart2P.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
